# Multi-Port Configuration Example for RustIRCd
# This example shows how to configure multiple ports with different settings

[server]
name = "example.irc.net"
description = "Example IRC Network with Multi-Port Support"
version = "0.1.0"
created = "2025-01-01 00:00:00 UTC"
max_clients = 5000
max_channels_per_client = 20
max_channel_name_length = 200
max_nickname_length = 9
max_topic_length = 390
max_away_length = 160
max_kick_length = 160
max_quit_length = 160

[network]
name = "ExampleNet"
description = "Example IRC Network"
links = []
operators = [
    { name = "admin", password = "secure_password", hostmask = "*@*", privileges = ["all"] },
    { name = "helper", password = "helper_pass", hostmask = "*@trusted.net", privileges = ["kick", "ban", "op"] }
]
super_servers = [
    { name = "services.example.net", hostname = "services.example.net", port = 6669, password = "services_secure", tls = true, privileges = ["all"] }
]

[connection]
bind_address = "0.0.0.0"
connection_timeout = 60
ping_timeout = 300
max_connections_per_ip = 10
max_connections_per_host = 20

# Multiple ports with different configurations
[[connection.ports]]
port = 6667
connection_type = "Client"
tls = false
description = "Standard IRC port for legacy clients"

[[connection.ports]]
port = 6697
connection_type = "Client"
tls = true
description = "Secure IRC port for modern clients"

[[connection.ports]]
port = 6668
connection_type = "Server"
tls = false
description = "Server-to-server connections (insecure)"

[[connection.ports]]
port = 6698
connection_type = "Server"
tls = true
description = "Secure server-to-server connections"

[[connection.ports]]
port = 8080
connection_type = "Both"
tls = false
description = "WebSocket IRC port (future feature)"

[[connection.ports]]
port = 8443
connection_type = "Both"
tls = true
description = "Secure WebSocket IRC port (future feature)"

[security]
allowed_hosts = ["*"]
denied_hosts = ["*.spam.net", "malicious.com"]
require_client_password = false
client_password = ""
enable_ident = true
enable_dns = true
enable_reverse_dns = true

[security.tls]
enabled = true
cert_file = "/etc/ssl/certs/irc.crt"
key_file = "/etc/ssl/private/irc.key"
ca_file = "/etc/ssl/certs/ca-bundle.crt"
version = "1.3"
cipher_suites = [
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
    "TLS_AES_128_GCM_SHA256"
]

[modules]
module_directory = "modules"
enabled_modules = ["channel", "ircv3", "optional"]
module_settings = {
    channel = { max_channels_per_user = 20, default_channel_modes = "nt" },
    ircv3 = { enable_sasl = true, enable_batch = true },
    optional = { enable_away = true, enable_ison = true }
}

[database]
max_history_size = 10000
history_retention_days = 30
enable_channel_tracking = true
enable_activity_tracking = true

[broadcast]
max_concurrent_queries = 100
query_timeout_seconds = 30
enable_network_queries = true
enable_efficient_broadcasting = true

[services]
services_directory = "services"
enabled_services = ["nickserv", "chanserv", "memoserv"]
service_settings = {
    nickserv = { max_nick_length = 31, enable_auto_register = false },
    chanserv = { max_channel_length = 50, enable_auto_register = false },
    memoserv = { max_memo_length = 400, max_memos_per_user = 50 }
}
