# Full configuration - all modules enabled

[server]
name = "full.local"
description = "Full-Featured IRC Daemon"
version = "0.1.0"
created = "2024-01-01 00:00:00 UTC"
max_clients = 1000
max_channels_per_client = 10
max_channel_name_length = 200
max_nickname_length = 9
max_topic_length = 390
max_away_length = 160
max_kick_length = 160
max_quit_length = 160

[network]
name = "FullNet"
description = "Full-Featured IRC Network"
links = [
    { name = "server2.example.com", hostname = "server2.example.com", port = 6668, password = "link123", tls = false, outgoing = true }
]
operators = [
    { name = "admin", password = "admin123", hostmask = "*@*", privileges = ["all"] },
    { name = "helper", password = "helper123", hostmask = "*@*.example.com", privileges = ["kick", "ban"] }
]
super_servers = [
    { name = "services.example.com", hostname = "services.example.com", port = 6669, password = "services123", tls = false, privileges = ["all"] },
    { name = "stats.example.com", hostname = "stats.example.com", port = 6670, password = "stats123", tls = true, privileges = ["stats"] }
]

[connection]
client_port = 6667
server_port = 6668
client_tls_port = 6697
server_tls_port = 6698
bind_address = "0.0.0.0"
connection_timeout = 60
ping_timeout = 300
max_connections_per_ip = 5
max_connections_per_host = 10

[security]
allowed_hosts = ["*"]
denied_hosts = ["*.spam.com"]
require_client_password = false
client_password = ""
enable_ident = true
enable_dns = true
enable_reverse_dns = true

[tls]
enabled = true
cert_file = "cert.pem"
key_file = "key.pem"
ca_file = "ca.pem"
version = "1.3"
cipher_suites = ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256"]

[modules]
module_directory = "modules"
enabled_modules = ["channel", "ircv3", "optional"]  # All modules enabled
module_settings = {
    channel = { max_channels_per_user = 10, default_modes = "+nt" },
    ircv3 = { capabilities = ["cap", "sasl", "account-tag"] },
    optional = { enable_away = true, enable_ison = true }
}

[services]
services_directory = "services"
enabled_services = ["example", "nickserv", "chanserv"]
service_settings = {
    example = { debug = true },
    nickserv = { database = "sqlite://nickserv.db" },
    chanserv = { database = "sqlite://chanserv.db" }
}
