# Messaging Disabled Configuration
# This configuration disables all messaging modules

[modules.messaging]
enabled = false

[modules.messaging.wallops]
enabled = false
require_operator = true
receiver_mode = null
self_only_mode = true
mode_requires_operator = false

[modules.messaging.globops]
enabled = false
require_operator = true
receiver_mode = null
self_only_mode = true
mode_requires_operator = false
