# Custom Modes Configuration
# This configuration uses different mode characters and custom settings

[modules.messaging]
enabled = true

[modules.messaging.wallops]
enabled = true
require_operator = true
receiver_mode = "x"  # Custom mode character
self_only_mode = true
mode_requires_operator = false  # Users can set +x themselves (wallops behavior)

[modules.messaging.globops]
enabled = true
require_operator = true
receiver_mode = "y"  # Custom mode character
self_only_mode = false  # Operators can set +y on others
mode_requires_operator = true  # Only operators can set +y (globops behavior)
