# Minimal configuration - no channels, basic IRC only

[server]
name = "minimal.local"
description = "Minimal IRC Daemon"
version = "0.1.0"
created = "2024-01-01 00:00:00 UTC"
max_clients = 100
max_channels_per_client = 0  # No channels
max_channel_name_length = 200
max_nickname_length = 9
max_topic_length = 390
max_away_length = 160
max_kick_length = 160
max_quit_length = 160

[network]
name = "MinimalNet"
description = "Minimal IRC Network"
links = []
operators = []
super_servers = []

[connection]
client_port = 6667
server_port = 0  # No server connections
client_tls_port = 6697
server_tls_port = 0
bind_address = "0.0.0.0"
connection_timeout = 60
ping_timeout = 300
max_connections_per_ip = 5
max_connections_per_host = 10

[security]
allowed_hosts = ["*"]
denied_hosts = []
require_client_password = false
client_password = ""
enable_ident = true
enable_dns = true
enable_reverse_dns = true

[tls]
enabled = false
cert_file = ""
key_file = ""
ca_file = ""
version = "1.3"
cipher_suites = ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256"]

[modules]
module_directory = "modules"
enabled_modules = []  # No modules - basic IRC only
module_settings = {}

[services]
services_directory = "services"
enabled_services = []
service_settings = {}
