# Example configuration with absolute MOTD file path
# This demonstrates using an absolute path for the MOTD file

[server]
name = "absolute.example.com"
description = "Rust IRC Daemon with Absolute MOTD Path"
version = "1.0.0"
created = "2024-01-01 00:00:00 UTC"
max_clients = 1000
max_channels_per_client = 10
max_channel_name_length = 200
max_nickname_length = 9
max_topic_length = 390
max_away_length = 160
max_kick_length = 160
max_quit_length = 160
admin_email = "admin@absolute.example.com"
admin_location1 = "Absolute Path IRC Network"
admin_location2 = "https://github.com/rustircd/rustircd"

# MOTD Configuration with Absolute Path
# Unix/Linux absolute path example
motd_file = "/etc/rustircd/motd.txt"

# Alternative absolute path examples:
# Windows: motd_file = "C:\\Program Files\\RustIRCd\\motd.txt"
# macOS: motd_file = "/usr/local/etc/rustircd/motd.txt"
# Custom location: motd_file = "/opt/rustircd/config/motd.txt"

[network]
name = "AbsoluteNet"
description = "IRC Network with Absolute MOTD Path"

[[network.operators]]
nickname = "admin"
password_hash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # "password" in SHA256
hostmask = "admin@*"
flags = ["o", "O", "a", "A", "r", "R", "w", "W", "c", "C", "h", "H", "s", "S", "n", "N", "f", "F", "x", "X"]

[connection]
ports = [
    { port = 6667, connection_type = "Client", tls = false, description = "Standard IRC port" }
]

[security]
require_registration = true
max_connections_per_ip = 5

[modules]
enabled_modules = ["throttling", "channel", "ircv3"]
module_directory = "modules"

[modules.throttling]
enabled = true
max_connections_per_ip = 3
time_window_seconds = 60
initial_throttle_seconds = 10
max_stages = 10
stage_factor = 10
cleanup_interval_seconds = 300

[database]
enabled = false

[broadcast]
enabled = false

[services]
enabled = false
