# Example configuration with MOTD support
# This configuration demonstrates how to configure and use MOTD (Message of the Day)

[server]
name = "motd.example.com"
description = "Rust IRC Daemon with MOTD Support"
version = "1.0.0"
created = "2024-01-01 00:00:00 UTC"
max_clients = 1000
max_channels_per_client = 10
max_channel_name_length = 200
max_nickname_length = 9
max_topic_length = 390
max_away_length = 160
max_kick_length = 160
max_quit_length = 160
admin_email = "admin@motd.example.com"
admin_location1 = "MOTD IRC Network"
admin_location2 = "https://github.com/rustircd/rustircd"

# MOTD Configuration
# Path to the MOTD file - supports both relative and absolute paths
# Relative paths are resolved from server working directory
# Absolute paths are used as-is
# If not specified or file doesn't exist, no MOTD will be shown
motd_file = "motd.txt"  # Relative path example
# motd_file = "/etc/rustircd/motd.txt"  # Absolute path example (Unix)
# motd_file = "C:\\Program Files\\RustIRCd\\motd.txt"  # Absolute path example (Windows)

# Security setting for STATS commands
show_server_details_in_stats = true

[network]
name = "MOTDNet"
description = "MOTD IRC Network with Example Configuration"

[[network.operators]]
nickname = "admin"
password_hash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # "password" in SHA256
hostmask = "admin@*"
flags = ["o", "O", "a", "A", "r", "R", "w", "W", "c", "C", "h", "H", "s", "S", "n", "N", "f", "F", "x", "X"]

[connection]
ports = [
    { port = 6667, connection_type = "Client", tls = false, description = "Standard IRC port with MOTD" }
]

[security]
# Additional security settings
require_registration = true
max_connections_per_ip = 5

[modules]
enabled_modules = ["throttling", "channel", "ircv3"]
module_directory = "modules"

# Throttling configuration
[modules.throttling]
enabled = true
max_connections_per_ip = 3
time_window_seconds = 60
initial_throttle_seconds = 10
max_stages = 10
stage_factor = 10
cleanup_interval_seconds = 300

[database]
enabled = false

[broadcast]
enabled = false

[services]
enabled = false
