# Example configuration with relative MOTD file path
# This demonstrates using relative paths for the MOTD file

[server]
name = "relative.example.com"
description = "Rust IRC Daemon with Relative MOTD Path"
version = "1.0.0"
created = "2024-01-01 00:00:00 UTC"
max_clients = 1000
max_channels_per_client = 10
max_channel_name_length = 200
max_nickname_length = 9
max_topic_length = 390
max_away_length = 160
max_kick_length = 160
max_quit_length = 160
admin_email = "admin@relative.example.com"
admin_location1 = "Relative Path IRC Network"
admin_location2 = "https://github.com/rustircd/rustircd"

# MOTD Configuration with Relative Path
# Relative paths are resolved from the server's working directory
motd_file = "config/messages/motd.txt"

# Alternative relative path examples:
# motd_file = "motd.txt"                    # Same directory as server
# motd_file = "messages/welcome.txt"        # Subdirectory
# motd_file = "../shared/motd.txt"          # Parent directory
# motd_file = "data/text/motd.txt"          # Multiple subdirectories

[network]
name = "RelativeNet"
description = "IRC Network with Relative MOTD Path"

[[network.operators]]
nickname = "admin"
password_hash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # "password" in SHA256
hostmask = "admin@*"
flags = ["o", "O", "a", "A", "r", "R", "w", "W", "c", "C", "h", "H", "s", "S", "n", "N", "f", "F", "x", "X"]

[connection]
ports = [
    { port = 6667, connection_type = "Client", tls = false, description = "Standard IRC port" }
]

[security]
require_registration = true
max_connections_per_ip = 5

[modules]
enabled_modules = ["throttling", "channel", "ircv3"]
module_directory = "modules"

[modules.throttling]
enabled = true
max_connections_per_ip = 3
time_window_seconds = 60
initial_throttle_seconds = 10
max_stages = 10
stage_factor = 10
cleanup_interval_seconds = 300

[database]
enabled = false

[broadcast]
enabled = false

[services]
enabled = false
