# Solanum Extensions Configuration Example
# This configuration shows how to set up IP cloaking and OPME extensions
# based on Solanum's 4.0c implementation

[server]
name = "solanum.example.ircd.org"
description = "Rust IRC Daemon with Solanum Extensions"
version = "0.1.0"
created = "2024-01-01 00:00:00 UTC"
max_clients = 1000
max_channels_per_client = 10
max_channel_name_length = 200
max_nickname_length = 9
max_topic_length = 390
max_away_length = 160
max_kick_length = 160
max_quit_length = 160
admin_email = "admin@solanum.example.ircd.org"
admin_location1 = "Solanum-Inspired IRC Network"
admin_location2 = "https://github.com/rustircd/rustircd"
show_server_details_in_stats = true
motd_file = "motd.txt"

[network]
name = "SolanumNet"
description = "Solanum-Inspired IRC Network"
links = []
operators = [
    { nickname = "admin", password_hash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8", hostmask = "*@*", flags = ["GlobalOper", "Administrator"], enabled = true }
]
super_servers = []

[connection]
ports = [
    { port = 6667, connection_type = "Client", tls = false, description = "Standard IRC port" },
    { port = 6697, connection_type = "Client", tls = true, description = "Secure IRC port" },
    { port = 6666, connection_type = "Server", tls = false, description = "Server-to-server connections" },
    { port = 6696, connection_type = "Server", tls = true, description = "Secure server-to-server connections" }
]
bind_address = "0.0.0.0"
connection_timeout = 60
ping_timeout = 300
max_connections_per_ip = 5
max_connections_per_host = 10

[security]
allowed_hosts = ["*"]
denied_hosts = []
require_client_password = false
client_password = null
enable_ident = true
enable_dns = true
enable_reverse_dns = true

[security.tls]
enabled = true
cert_file = "cert.pem"
key_file = "key.pem"
ca_file = null
version = "1.3"
cipher_suites = ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256"]

[security.server_security]
allow_remote_connect = true
require_oper_for_connect = true
allowed_remote_hosts = ["*"]
denied_remote_hosts = []
max_hop_count = 10
require_server_auth = true

[modules]
module_directory = "modules"
enabled_modules = ["oper", "sasl", "opme", "channel", "help", "admin"]
module_settings = {}

[modules.throttling]
enabled = true
max_connections_per_ip = 5
time_window_seconds = 60
initial_throttle_seconds = 10
max_stages = 10
stage_factor = 10
cleanup_interval_seconds = 300

# IP Cloaking Extension Configuration
[modules.ip_cloak]
enabled = true
secret_key = "change_this_secret_key_to_something_secure"
suffix = ".cloaked"
ipv4_cidr = 16
ipv6_cidr = 32
mac_bits = 64
preserve_patterns = [
    "*.example.ircd.org",
    "*.localhost",
    "*.local"
]

# OPME Extension Configuration
[modules.opme]
enabled = true
require_oper = true
log_usage = true
notify_channel = true
rate_limit_enabled = true
rate_limit_max_uses = 5
rate_limit_time_window = 300

[database]
max_history_size = 10000
history_retention_days = 30
enable_channel_tracking = true
enable_activity_tracking = true

[broadcast]
max_concurrent_queries = 100
query_timeout_seconds = 30
enable_network_queries = true
enable_efficient_broadcasting = true

# Services Configuration
[services]
services_directory = "services"
enabled_services = ["atheme"]

# Service Definitions
[[services.services]]
name = "services.example.ircd.org"
service_type = "atheme"
hostname = "localhost"
port = 6666
password = "atheme_password"
tls = false
enabled = true

[services.services.config]
# Atheme-specific configuration
service_name = "services.example.ircd.org"
protocol = "charybdis"
uplink_name = "solanum.example.ircd.org"
send_password = "atheme_password"
receive_password = "ircd_password"
flags = ["topicburst"]
class = "server"

# Service-specific settings
[services.service_settings]
atheme = {
    enabled = true,
    protocol = "charybdis",
    uplink_name = "solanum.example.ircd.org",
    send_password = "atheme_password",
    receive_password = "ircd_password",
    flags = ["topicburst"],
    class = "server",
    timeout_seconds = 30,
    reconnect_interval = 60,
    max_reconnect_attempts = 10
}

# Extension-specific settings
[extensions]
# Core extensions are automatically loaded
core_extensions = ["identify-msg", "account-tracking", "server-time", "batch", "ip-cloak"]

# IP Cloaking extension settings
[extensions.ip_cloak]
enabled = true
method = "hash"  # static, hash, hybrid, custom
secret_key = "my_very_secure_secret_key_12345"
suffix = ".myircd.org"
ipv4_cidr = 16
ipv6_cidr = 32
mac_bits = 64
preserve_hostname_patterns = [
    "*.myircd.org",
    "*.localhost",
    "*.local"
]

# Account tracking extension settings
[extensions.account_tracking]
enabled = true
service_name = "services.example.ircd.org"

# Identify message extension settings
[extensions.identify_msg]
enabled = true
service_name = "services.example.ircd.org"
add_to_all_messages = true

# Server time extension settings
[extensions.server_time]
enabled = true
add_to_all_messages = true

# Batch extension settings
[extensions.batch]
enabled = true
