# Example configuration for operators with SQUIT privileges
# This file demonstrates how to configure operators with the S flag for SQUIT command

[server]
name = "example.server.com"
description = "Example IRC Server with SQUIT Support"
hostname = "example.server.com"
port = 6667
max_clients = 1000

[network]
# Server links configuration
[[network.server_links]]
name = "remote.server.com"
hostname = "remote.server.com"
port = 6667
password = "link_password"
outgoing = true

# Super servers (u-lined servers)
[[network.super_servers]]
name = "super.server.com"
hostname = "super.server.com"
port = 6667
password = "super_password"
outgoing = true

# Operator configurations with different privilege levels
[[network.operators]]
nickname = "admin"
password_hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"  # SHA256 of "admin123"
hostmask = "*@*"
flags = ["GlobalOper", "Squit", "Administrator", "Spy"]
enabled = true

[[network.operators]]
nickname = "serverop"
password_hash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f"  # SHA256 of "serverop123"
hostmask = "*@trusted.host.com"
flags = ["LocalOper", "Squit", "RemoteConnect", "LocalConnect"]
enabled = true

[[network.operators]]
nickname = "regularop"
password_hash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # SHA256 of "hello"
hostmask = "*@localhost"
flags = ["LocalOper"]
enabled = true

# Security configuration
[security]
# Server security settings
[security.server_security]
allowed_remote_hosts = ["*.trusted.network.com", "192.168.1.0/24"]
denied_remote_hosts = ["*.bad.network.com"]

# Client security settings
[security.client_security]
max_channels_per_user = 10
max_nick_length = 30
max_topic_length = 300

# Throttling settings
[throttling]
max_connections_per_ip = 5
connection_throttle_duration = 60
message_throttle_duration = 1
max_messages_per_duration = 10

# Statistics configuration
[statistics]
enabled = true
log_level = "info"
log_file = "server_stats.log"

# MOTD configuration
[motd]
enabled = true
file_path = "motd.txt"

# Database configuration
[database]
type = "memory"
path = "server.db"
