# Example configuration with STATS security settings
# This configuration demonstrates how to control information disclosure in STATS commands

[server]
name = "secure.example.com"
description = "Secure IRC Server with Controlled STATS"
version = "1.0.0"
created = "2024-01-01 00:00:00 UTC"
max_clients = 1000
max_channels_per_client = 10
max_channel_name_length = 200
max_nickname_length = 9
max_topic_length = 390
max_away_length = 160
max_kick_length = 160
max_quit_length = 160
admin_email = "admin@secure.example.com"
admin_location1 = "Secure IRC Network"
admin_location2 = "https://github.com/rustircd/rustircd"

# SECURITY SETTING: Control server IP/hostname disclosure in STATS
# When set to false, even operators will not see server IPs/hostnames in STATS commands
# When set to true (default), operators can see full server details in STATS commands
show_server_details_in_stats = false

[network]
name = "SecureNet"
description = "Secure IRC Network with Controlled Information Disclosure"

[[network.operators]]
nickname = "admin"
password_hash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # "password" in SHA256
hostmask = "admin@*"
flags = ["o", "O", "a", "A", "r", "R", "w", "W", "c", "C", "h", "H", "s", "S", "n", "N", "f", "F", "x", "X"]

[connection]
ports = [
    { port = 6667, connection_type = "Client", tls = false, description = "Secure client port" }
]

[security]
# Additional security settings
require_registration = true
max_connections_per_ip = 5

[modules]
enabled_modules = ["throttling", "channel", "ircv3"]
module_directory = "modules"

# Throttling configuration for enhanced security
[modules.throttling]
enabled = true
max_connections_per_ip = 3
time_window_seconds = 60
initial_throttle_seconds = 10
max_stages = 10
stage_factor = 10
cleanup_interval_seconds = 300

[database]
enabled = false

[broadcast]
enabled = false

[services]
enabled = false
