# Example configuration with throttling module enabled
# This configuration demonstrates how to configure connection throttling

[server]
name = "throttling.example.com"
description = "Rust IRC Daemon with Throttling"
version = "1.0.0"
created = "2024-01-01 00:00:00 UTC"
max_clients = 1000
max_channels_per_client = 10
max_channel_name_length = 200
max_nickname_length = 9
max_topic_length = 390
max_away_length = 160
max_kick_length = 160
max_quit_length = 160
admin_email = "admin@throttling.example.com"
admin_location1 = "Throttling IRC Network"
admin_location2 = "https://github.com/rustircd/rustircd"

[network]
name = "ThrottlingNet"
description = "Throttling IRC Network"
# No server links in this example

[[network.operators]]
nickname = "admin"
password_hash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # "password" in SHA256
hostmask = "admin@*"
flags = ["GlobalOper", "LocalOper", "RemoteConnect", "LocalConnect", "Administrator", "Spy"]
enabled = true

[connection]
bind_address = "0.0.0.0"
connection_timeout = 60
ping_timeout = 300
max_connections_per_ip = 5
max_connections_per_host = 10

# Configure multiple ports
[[connection.ports]]
port = 6667
connection_type = "Client"
tls = false
description = "Standard IRC port"

[[connection.ports]]
port = 6697
connection_type = "Client"
tls = true
description = "Secure IRC port"

[[connection.ports]]
port = 6668
connection_type = "Server"
tls = false
description = "Server-to-server connections"

[security]
allowed_hosts = ["*"]
denied_hosts = []
require_client_password = false
client_password = null
enable_ident = true
enable_dns = true
enable_reverse_dns = true

[security.tls]
enabled = true
cert_file = "certs/server.crt"
key_file = "certs/server.key"
ca_file = null
version = "1.3"
cipher_suites = ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256"]

[security.server_security]
allow_remote_connect = true
require_oper_for_connect = true
allowed_remote_hosts = ["*"]
denied_remote_hosts = []
max_hop_count = 10
require_server_auth = true

[database]
max_history_size = 10000
history_retention_days = 30
enable_channel_tracking = true
enable_activity_tracking = true

[broadcast]
max_concurrent_queries = 100
query_timeout_seconds = 30
enable_network_queries = true
enable_efficient_broadcasting = true

[services]
services_directory = "services"
enabled_services = []
# No service settings in this example

# Module configuration with throttling enabled
[modules]
module_directory = "modules"
enabled_modules = ["throttling", "channel", "ircv3", "optional"]

# Throttling configuration
[modules.throttling]
# Enable throttling module
enabled = true

# Maximum number of connections allowed per IP within the time window
max_connections_per_ip = 5

# Time window in seconds for connection counting
time_window_seconds = 60

# Initial throttling duration in seconds (stage 1)
initial_throttle_seconds = 10

# Maximum number of throttling stages
max_stages = 10

# Factor by which throttling increases between stages
stage_factor = 10

# Cleanup interval in seconds for expired throttle entries
cleanup_interval_seconds = 300

# Example of different throttling configurations:

# Conservative throttling (strict limits)
# max_connections_per_ip = 3
# time_window_seconds = 120
# initial_throttle_seconds = 30
# max_stages = 5
# stage_factor = 5

# Relaxed throttling (more permissive)
# max_connections_per_ip = 10
# time_window_seconds = 30
# initial_throttle_seconds = 5
# max_stages = 15
# stage_factor = 15

# Aggressive throttling (very strict)
# max_connections_per_ip = 2
# time_window_seconds = 300
# initial_throttle_seconds = 60
# max_stages = 8
# stage_factor = 8
